name: Build and Deploy Hugo site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read        # checkout source
  pages: write          # allow Pages deployments
  id-token: write       # required by deploy-pages action

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-pages.outputs.artifact_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.150.0'
          extended: true

      - name: Build Hugo site
        # build inside the repo root; if your site is in a subfolder, `working-directory: <folder>`
        run: hugo --minify

      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        #with:
          # default behavior uses the artifact created by upload-pages-artifact in the build job
          # no inputs required for the common case
